BuroFactor/Areas/Reporte/Controllers/BuroController.cs
using BuroFactor.code.dao;
using BuroFactor.code.extension.html;
using BuroFactor.code.service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace BuroFactor.Areas.Reporte.Controllers
{
    [Security(Roles = "FINANCIERA", NotifyUrl = "~/Principal/Errores/Error404")]
    public class BuroController : Controller
    {
        // GET: Reporte/Buro
        public ActionResult Index()
        {

            return View();
        }
        public ActionResult Visualizar(BuroFactor.Areas.Reporte.Models.ConsultaBuro consulta)
        {
            IDaoCore daoCoreProvider = ServiceBuro.Instance.DaoCore;
            using (IDaoCore daoCore = daoCoreProvider.Create((User.Identity as ClaimsIdentity).Claims.FirstOrDefault(p => p.Type == ClaimTypes.NameIdentifier).Value))
            {
                var response = daoCore.ConsultaBuro(consulta.RFC);
                if (response != null)
                {
                    return View(response);
                }
            }
            return null;
        }
    }
}

BuroFactor/Areas/Reporte/Views/Buro/Index.cshtml
@model BuroFactor.Areas.Reporte.Models.ConsultaBuro

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Visualizar", "Buro"))
{

    <div class="form-horizontal">
        <h4>Consulta Buro</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.RFC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RFC, new { htmlAttributes = new { @class = "form-control", placeholder= "CAL0206045G9"  } })
                @Html.ValidationMessageFor(model => model.RFC, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="checkbox" id="Aceptar" style="margin-left: 57%;" ng-model="checked" /><label  style="margin-left: 57%;" for="Aceptar">Aceptar terminos</label>
                <br />
                <input type="submit" value="Consultar" class="btn btn-default" 
                       style="margin-left: 57%; margin-top: 3%;"
                       ng-disabled="!checked" ng-click="" />
            </div>
        </div>
    </div>
    
}
<div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BuroFactor/Areas/Reporte/Views/Buro/Visualizar.cshtml
@model BuroFactor.BuroService.BuroResponse
@{
    ViewBag.Title = "Visualizar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (Model != null && !String.IsNullOrEmpty(Model.RazonSocial))
{
    <div>
        <h1>Resultados</h1>
        <h2 style="font-weight:bolder">Datos Generales</h2>
        <br />
        <div class="table-responsive">
            <table class="table table-striped">
                <tr>
                    <td style="font-weight:bolder">Razon Social</td>
                    <td>@Model.RazonSocial</td>
                </tr>
                <tr>
                    <td style="font-weight:bolder">RFC</td>
                    <td>@Model.RFC</td>
                </tr>
                <tr>
                    <td style="font-weight:bolder">Fecha Constitucion</td>
                    <td>@Model.FechaConstitucion.ToString("d")</td>
                </tr>
            </table>
        </div>
        <br />
        <h6 style="font-weight:bolder">Resumen</h6>
        <br />

        <table class="table table-striped">
            <thead>
                <tr><td>Financiera</td><td>RFC</td><td>Monto Financiado</td><td>Monto Pagado</td><td>Monto Deuda</td><td>Es Moroso</td></tr>
            </thead>
            @foreach (var relacion in Model.Relacion)
            {
                <tbody>
                    @{
                        bool isMoroso = relacion.Operaciones.Any(p => p.FechaVencimiento < DateTime.Now);
                        string style = !isMoroso ? "background-color:Red" : null;
                    }
                    <tr style="@isMoroso">
                        <td>@relacion.Financiera.RazonSocial</td>
                        <td>@relacion.Financiera.RFC</td>
                        <td>@String.Format("{0:c}", relacion.Operaciones.Sum(aux => aux.MontoFinanciado))</td>
                        <td>@relacion.Operaciones.Where(p => p.Historial.Any(s => s.Tipo == "P")).Sum(aux => aux.MontoFinanciado)</td>
                        <td>
                            @String.Format("{0:c}", (relacion.Operaciones.Sum(aux => aux.MontoFinanciado) - relacion.Operaciones.Where(p => p.Historial.Any(s => s.Tipo == "P")).Sum(aux => aux.MontoFinanciado)))
                        </td>
                        <td>
                            @(isMoroso ? "Si" : "No")
                        </td>
                    </tr>
                </tbody>
                        }

        </table>

        <br />
        <br />

        <button class="btn btn-primary" style="margin-left:60%" type="button" onclick="window.print();">
            <i class="large material-icons">print</i>
        </button>
        <button class="btn btn-primary" type="button" onclick="window.history.go(-1);">
            <i class="large material-icons">replay</i>
        </button>


    </div>
                        }
                        else
                        {
                            <script>
                                alertify.alert("No hay resultados", function () {
                                    window.history.go(-1);
                                });

                            </script>
                        }